import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import '../services/firebase_service.dart';

class ChangePasswordScreen extends StatefulWidget{const ChangePasswordScreen({super.key});@override State<ChangePasswordScreen> createState()=>_ChangePasswordScreenState();}
class _ChangePasswordScreenState extends State<ChangePasswordScreen>{
  static const navy=Color(0xFF12305D),blue=Color(0xFF1173EA);final current=TextEditingController(),next=TextEditingController(),confirm=TextEditingController();bool loading=false;
  Future<void> update()async{if(next.text.length<8||next.text!=confirm.text){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Passwords must match and contain at least 8 characters.')));return;}setState(()=>loading=true);try{final user=FirebaseService.auth.currentUser!,email=user.email!;await user.reauthenticateWithCredential(EmailAuthProvider.credential(email:email,password:current.text));await user.updatePassword(next.text);if(mounted){Navigator.pop(context);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Password updated successfully.')));}}on FirebaseAuthException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message??'Could not update password.')));}finally{if(mounted)setState(()=>loading=false);}}
  @override void dispose(){current.dispose();next.dispose();confirm.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF4F7FD),appBar:AppBar(backgroundColor:Colors.white,centerTitle:true,leading:IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_ios_new_rounded,color:navy)),title:const Text('Change Password',style:TextStyle(color:navy,fontWeight:FontWeight.w800))),body:Padding(padding:const EdgeInsets.all(22),child:Column(children:[_field('Current Password',current),const SizedBox(height:17),_field('New Password',next),const SizedBox(height:17),_field('Confirm New Password',confirm),const Spacer(),SizedBox(width:double.infinity,height:54,child:ElevatedButton(onPressed:loading?null:update,style:ElevatedButton.styleFrom(backgroundColor:blue,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12))),child:loading?const CircularProgressIndicator(color:Colors.white):const Text('Update Password',style:TextStyle(fontWeight:FontWeight.w800))))])));
  Widget _field(String label,TextEditingController c)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(color:navy,fontWeight:FontWeight.w700)),const SizedBox(height:7),TextField(controller:c,obscureText:true,decoration:InputDecoration(prefixIcon:const Icon(Icons.lock_outline),filled:true,fillColor:Colors.white,enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:const BorderSide(color:Color(0xFFD8E0EA))),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:const BorderSide(color:blue))))]);
}
