import 'package:flutter/material.dart';
import '../services/firebase_service.dart';

class EditProfileScreen extends StatefulWidget{const EditProfileScreen({super.key});@override State<EditProfileScreen> createState()=>_EditProfileScreenState();}
class _EditProfileScreenState extends State<EditProfileScreen>{
  static const navy=Color(0xFF12305D),blue=Color(0xFF1173EA);final name=TextEditingController(),phone=TextEditingController();bool loading=true,saving=false;
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{final d=await FirebaseService.db.collection('users').doc(FirebaseService.uid).get();name.text='${d.data()?['fullName']??''}';phone.text='${d.data()?['phone']??''}';if(mounted)setState(()=>loading=false);}
  Future<void> _save()async{if(name.text.trim().isEmpty||phone.text.trim().isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Please complete all fields.')));return;}setState(()=>saving=true);try{await FirebaseService.updateProfile(fullName:name.text,phone:phone.text);if(mounted)Navigator.pop(context);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Update failed: $e')));}finally{if(mounted)setState(()=>saving=false);}}
  @override void dispose(){name.dispose();phone.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF4F7FD),appBar:AppBar(backgroundColor:Colors.white,centerTitle:true,leading:IconButton(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_ios_new_rounded,color:navy)),title:const Text('Edit Profile',style:TextStyle(color:navy,fontWeight:FontWeight.w800))),body:loading?const Center(child:CircularProgressIndicator()):Padding(padding:const EdgeInsets.all(22),child:Column(children:[
    const CircleAvatar(radius:54,backgroundImage:AssetImage('assets/images/profile.png')),const SizedBox(height:30),_field('Full Name',name,Icons.person_outline),const SizedBox(height:16),_field('Phone Number',phone,Icons.phone_outlined),const Spacer(),SizedBox(width:double.infinity,height:54,child:ElevatedButton(onPressed:saving?null:_save,style:ElevatedButton.styleFrom(backgroundColor:blue,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12))),child:saving?const CircularProgressIndicator(color:Colors.white):const Text('Save Changes',style:TextStyle(fontSize:16,fontWeight:FontWeight.w800))))])));
  Widget _field(String label,TextEditingController c,IconData icon)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(color:navy,fontWeight:FontWeight.w700)),const SizedBox(height:7),TextField(controller:c,decoration:InputDecoration(prefixIcon:Icon(icon),filled:true,fillColor:Colors.white,enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:const BorderSide(color:Color(0xFFD8E0EA))),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(12),borderSide:const BorderSide(color:blue))))]);
}
