import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import '../services/firebase_service.dart';
import '../widgets/car_image.dart';
import 'office_bottom_nav.dart';

class OfficeDashboardScreen extends StatelessWidget{
  const OfficeDashboardScreen({super.key});static const navy=Color(0xFF12305D),blue=Color(0xFF1173EA);
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:const Color(0xFFF4F7FD),body:SafeArea(bottom:false,child:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseService.officeCars(),builder:(_,carsSnap)=>StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:FirebaseService.officeBookings(),builder:(_,bookSnap){
    if(!carsSnap.hasData||!bookSnap.hasData)return const Center(child:CircularProgressIndicator());final cars=carsSnap.data!.docs,bookings=bookSnap.data!.docs;final available=cars.where((c)=>c.data()['status']=='Available').length;final pending=bookings.where((b)=>b.data()['status']=='pending').toList();
    return ListView(padding:const EdgeInsets.fromLTRB(16,18,16,28),children:[Container(height:85,padding:const EdgeInsets.symmetric(horizontal:16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Row(children:[Image.asset('assets/images/logo.png',width:46),const SizedBox(width:9),const Text.rich(TextSpan(children:[TextSpan(text:'Easy',style:TextStyle(color:navy)),TextSpan(text:'Rent',style:TextStyle(color:blue))]),style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const Spacer(),const CircleAvatar(radius:24,backgroundImage:AssetImage('assets/images/profile.png'))])),const SizedBox(height:22),const Text('Office Dashboard',style:TextStyle(color:navy,fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:15),
      Row(children:[Expanded(child:_Stat('Total Cars','${cars.length}')),const SizedBox(width:8),Expanded(child:_Stat('Available','$available')),const SizedBox(width:8),Expanded(child:_Stat('Bookings','${bookings.length}'))]),const SizedBox(height:27),const Text('Recent Booking Requests',style:TextStyle(color:navy,fontSize:21,fontWeight:FontWeight.w800)),const SizedBox(height:13),
      if(pending.isEmpty)const _Empty('No pending booking requests.') else ...pending.take(3).map((d)=>Padding(padding:const EdgeInsets.only(bottom:11),child:_DashCard(data:d.data()))),const SizedBox(height:15),const Text('Recently Added Cars',style:TextStyle(color:navy,fontSize:21,fontWeight:FontWeight.w800)),const SizedBox(height:13),if(cars.isEmpty)const _Empty('Add your first car from My Cars.')else...cars.take(3).map((d)=>Padding(padding:const EdgeInsets.only(bottom:11),child:_CarCard(data:d.data())))
    ]);
  }))),bottomNavigationBar:const OfficeBottomNav(currentIndex:0));
}
class _Stat extends StatelessWidget{final String title,value;const _Stat(this.title,this.value);@override Widget build(BuildContext context)=>Container(height:110,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(15)),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(title,style:const TextStyle(color:Color(0xFF64748B),fontSize:12)),const SizedBox(height:8),Text(value,style:const TextStyle(color:OfficeDashboardScreen.navy,fontSize:27,fontWeight:FontWeight.w900))]));}
class _DashCard extends StatelessWidget{final Map<String,dynamic> data;const _DashCard({required this.data});@override Widget build(BuildContext context)=>_base('${data['carName']??'Car'}','${data['customerName']??'Customer'}','Pending',true,data['imageUrl'] as String?);}
class _CarCard extends StatelessWidget{final Map<String,dynamic> data;const _CarCard({required this.data});@override Widget build(BuildContext context)=>_base('${data['name']??'Car'}','${data['category']??''} • ${data['transmission']??''}','${data['status']??'Available'}',false,data['imageUrl'] as String?);}
Widget _base(String title,String subtitle,String status,bool pending,String? imageUrl)=>Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:Row(children:[ClipRRect(borderRadius:BorderRadius.circular(11),child:CarImage(url:imageUrl,width:74,height:74)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(color:OfficeDashboardScreen.navy,fontWeight:FontWeight.w800)),const SizedBox(height:7),Text(subtitle,style:const TextStyle(color:Color(0xFF64748B),fontSize:11))])),Text(status,style:TextStyle(color:pending?const Color(0xFFB7791F):const Color(0xFF16A75C),fontSize:10,fontWeight:FontWeight.w700))]));
class _Empty extends StatelessWidget{final String text;const _Empty(this.text);@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16)),child:Text(text,textAlign:TextAlign.center,style:const TextStyle(color:Color(0xFF64748B))));}
